# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0003_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
